### ISSUE TITLE
Segmentation Fault in OpenGLTexture::recreateFromImageData()

### ISSUE THREAD

**Issue by phlip9** [ivansafrin/Polycode#345]
I'm trying to run the UpdateLoop example and I keep getting a segfault in the OpenGLTexture::recreateFromImageData() function. I've posted the stack trace if anyone wants to take a look.

(gdb) run
Starting program: /home/phlip9/Polycode/Release/Linux/Framework/Examples/Linux/UpdateLoop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
AL already initialized
[New Thread 0xb7fb3b40 (LWP 4098)]
[Thread 0xb7fb3b40 (LWP 4098) exited]
[New Thread 0xb7fb3b40 (LWP 4099)]
[New Thread 0xb35ffb40 (LWP 4100)]
OpenAL initialized...
Creating new core services instance...
Added archive: Resources/default.pak
Adding texture default

Program received signal SIGSEGV, Segmentation fault.
0x0044e66a in ?? () from /lib/i386-linux-gnu/libc.so.6
(gdb) backtrace
#0  0x0044e66a in ?? () from /lib/i386-linux-gnu/libc.so.6
#1  0x0044afaf in strtod () from /lib/i386-linux-gnu/libc.so.6
#2  0x001e7964 in ?? () from /usr/lib/i386-linux-gnu/libGLU.so.1
#3  0x001f3530 in gluBuild2DMipmaps () from /usr/lib/i386-linux-gnu/libGLU.so.1
#4  0x08099cf2 in Polycode::OpenGLTexture::recreateFromImageData() ()
#5  0x08099e6f in Polycode::OpenGLTexture::OpenGLTexture(unsigned int, unsigned int, char*, bool, bool, int, int) ()
#6  0x08094b11 in Polycode::OpenGLRenderer::createTexture(unsigned int, unsigned int, char*, bool, bool, int) ()
#7  0x08055266 in Polycode::MaterialManager::createTexture(int, int, char*, bool, bool, int) ()
#8  0x0805546b in Polycode::MaterialManager::createTextureFromFile(Polycode::String const&, bool, bool) ()
#9  0x0806bf3c in Polycode::ResourceManager::parseTextures(Polycode::String const&, bool, Polycode::String const&) ()
#10 0x0806cbeb in Polycode::ResourceManager::addDirResource(Polycode::String const&, bool) ()
#11 0x0804ef0c in HelloPolycodeApp::HelloPolycodeApp(Polycode::PolycodeView*) ()
#12 0x0804ede7 in main ()

**Comment by ljluestc** [comment]
```

#include "Polycode.h"
#include "PolycodeView.h"

using namespace Polycode;

// Application class
class HelloPolycodeApp {
public:
    HelloPolycodeApp(PolycodeView *view);
    ~HelloPolycodeApp();
    bool Update();

private:
    Core *core;              // Polycode core instance
    Scene *scene;            // 2D scene for rendering
    SceneSprite *sprite;     // Sprite to display texture
};

// Constructor
HelloPolycodeApp::HelloPolycodeApp(PolycodeView *view) {
    // Initialize the Polycode core (Linux-specific)
    core = new Polycore(view);

    // Add resource archive (ensure default.pak exists in the working directory)
    core->getServices()->getResourceManager()->addArchive("Resources/default.pak");
    core->getServices()->getResourceManager()->addDirResource("Resources", true);

    // Create a 2D scene
    scene = new Scene(Scene::SCENE_2D);

    // Load a texture and create a sprite
    Texture *texture = core->getServices()->getMaterialManager()->createTextureFromFile("default.png", false, false);
    if (!texture) {
        printf("Failed to load texture 'default.png'\n");
        return; // Avoid proceeding with null texture
    }

    sprite = new SceneSprite(texture);
    sprite->setPosition(400, 300); // Center-ish on an 800x600 screen
    scene->addChild(sprite);

    printf("Polycode app initialized.\n");
}

// Destructor
HelloPolycodeApp::~HelloPolycodeApp() {
    delete sprite;
    delete scene;
    delete core;
}

// Update loop
bool HelloPolycodeApp::Update() {
    Number elapsed = core->getElapsed();
    sprite->setRotation(sprite->getRotation() + elapsed * 50.0); // Rotate sprite
    return core->Update(); // Keep running unless core says stop
}

// Main function
int main(int argc, char *argv[]) {
    PolycodeView *view = new PolycodeView("UpdateLoop Example");
    HelloPolycodeApp *app = new HelloPolycodeApp(view);

    // Main loop (Polycode handles this internally)
    while (app->Update()) {
        // No manual loop needed; Polycode's core->Update() drives it
    }

    delete app;
    delete view;
    return 0;
}
​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​

```
